### ISSUE TITLE
Link generation bei subdir installation

### ISSUE THREAD

**Issue by pincy** [RRZE-Webteam/FAU-Techfak#16]
Falls die wordpress installation in einem Unterordner liegt und eine Testinstallation somit auf einen Unterordner zeigt, wird im wp_footer der Ordnername doppelt angeführt und der generierte Link für scripts.js geht ins leere.

Bsp: /wordpress/wordpress/wp-content/themes/FAU-Techfak/js/scripts.min.js?ver=1.6

Die Verwendung von absoluten Adressen schafft abhilfe und wird auch [hier](https://wordpress.org/support/topic/wp_footer-scripts-using-wrong-directory/) angeraten.

`diff --git a/functions.php b/functions.php`
`index f1f1d9f..2e2cba9 100644`
`--- a/functions.php`
`+++ b/functions.php`
`@@ -724,10 +724,10 @@ function fau_relativeimgurl_callback($matches) {`
`}`

 `function get_fau_template_uri () {`
`-     return wp_make_link_relative(get_template_directory_uri());`
`+     return get_template_directory_uri();`
`}`
`function fau_get_template_uri () {`
`-     return wp_make_link_relative(get_template_directory_uri());`
`+     return get_template_directory_uri();`
`}`

**Comment by xwolfde** [comment]
Wird im nächsten Merge im Master sein
