### ISSUE TITLE
Timeout beim Menuzuklappen

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/FAU-Techfak#24]
Ist es möglich, dass man einen Timeout einbaut, damit das ausgeklappte Menu (z.B. Forschung) beim Verlassen des Feldes nicht sofort zuklappt?

**Comment by xwolfde** [comment]
Ja, ist es. Aber wir haben es schonmal getestet und es kam nicht gut an und wurde dann wieder verworfen.
Wir können nochmal schauen ob wir da beim Schliessen ein Delay von 0.3s einbauen; Beim Öffnen sollte er aber dann bei 0 bleiben.

**Comment by xwolfde** [comment]
Das Theme wird an der stelle ggf. im Rahmen eines Auftrags an einen Experten nochmal feingetuned.
