### ISSUE TITLE
Conflict with WPCF7 Plugin

### ISSUE THREAD

**Issue by brandyman** [RRZE-Webteam/FAU-Techfak#26]
Hello,

I discovered an issue when using the theme with the WPCF7 plugin with a reCATPCHA authentication:
The following filter, starting in line 2031 leads to an error of the reCAPCHATA function:

`add_filter('the_content','remove_empty_p',20,1);`
`function remove_empty_p($content){`
`	$content = force_balance_tags($content);`
`	return preg_replace('#<p>\s*+(<br\s*/*>)?\s*</p>#i','',$content);`
`}`

Besides the regular reCAPTCHA field, a second field appears. The second field normally is wrapped in a noscript-tag, thus it is only shown, if no scripts are activated. However, in the output code, the noscript-tag is empty, wrapped in a `<p>`, and the code that should be in the noscript is in an `<div>` after the `<p>`.
The issue is caused by the `	$content = force_balance_tags($content);` line.

Is this function necessary (and if, how can the transformation of the noscript-blog be avoided), or can the function be commented out like in the following filters?

Best regards
Markus Brandmeier

**Comment by xwolfde** [comment]
I will look on it. We already have some other bugs in this field: https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/231 which belong together.
