### ISSUE TITLE
Metanavigation verschwindet in der mobilen Ansicht

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/FAU-Techfak#31]
Hallo,

in der mobilen Ansicht muss ich um die Sprache zu wechseln die Seite genau auf den Spalt zwischen Navigationsleiste und oberen Rand schieben. Wenn ich dann die Sprache wähle, geht ein Pull-Down-Menu nach unten unter die Navigationsleiste mit der neuen Sprache auf. Finde ich nicht so benutzerfreundlich.
Betrifft auch das FAU-Theme.
![img_2293](https://user-images.githubusercontent.com/20298307/28570006-7b754af6-713c-11e7-857a-9964d83f06c1.PNG)

**Comment by xwolfde** [comment]
Jepp, es laufen gerade Arbeiten, genau diese Probleme und weitere andere zu beheben...
(Der Spalt ist schon behoben.)
Bitte immer bei den Issues von FAU Einrichtungen eintragen, das TF Design ist nur ein Clon davon.

Referenz-Issue: https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/246
