### ISSUE TITLE
Flagge

### ISSUE THREAD

**Issue by anbininf12** [RRZE-Webteam/FAU-Techfak#35]
Hier war die Idee, statt des Logos beim Sprachwechsler die jeweilige Flagge einzublenden, weil das mehr ins Auge fällt.
Wahrscheinlich müsste man dazu den Sprachwechsler erweitern, damit man der jeweiligen Sprache eine Flagge zuweisen kann.

Grüße

Andreas

**Comment by xwolfde** [comment]
Dazu gab es hier eine episch lange Diskussion:
https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/177


Im Prinzip läuft es darauf hinaus, dass eine Landesflagge nicht eindeutig für die Sprache ist.
Deutsch wäre bspw. nicht eindeutig mit der Deutschland-Fahne zuordbar, weil da die Schweizer und Österreicher nicht mit dabei wären.
Die Britische Fahne ist für Englisch umstritten. Es müsste dann eher der Union Jack sein. Da ist aber erst recht der Streit vorhanden, da die Iren und Schotten eine eigene Sprache haben, aber auch unter dem UK Symbol fallen würden.
Amerikanische Flagge wäre ebenso ungünstig, da wir an der Uni als Standard Englisch-UK nutzen und nicht EN-US ..

Auch der Globus vorher war umstritten.
Das neue internationale Sprachsymbol, welches jetzt verwendet wird, setzt sich aber immer mehr durch, ist z.B. auch bei Facebook und G+ in Verwendung.


@RRZE-Webteam/fau-webredaktion  passend zusammengefasst?

**Comment by anbininf12** [comment]
Danke für die Info. So global haben wir das nicht gesehen. 100% Zustimmung

**Comment by xwolfde** [comment]
Sprachwechsel wurde geändert
