### ISSUE TITLE
Externe Links trotz deaktivierter Einstellung nicht im Menu

### ISSUE THREAD

**Issue by RosesTheN00b** [RRZE-Webteam/FAU-Techfak#41]
## Zusammenfassung:
Externe Links werden nicht im Menu angezeigt, obwohl die Einstellung entsprechend gesetzt war.

## Schritte zur Problemerzeugung:
- Externer Link in das Menu einfügen (hier: Link zum Lehrstuhl-Intranet)
- Folgende Option in den erweiterten Einstellungen aushaken:
> Links to other websites will be removed from the main menu. Please put external links in content menus, meta navigation, quicklinks or footer.
- Einstellung speichern
- Seite neu laden

## Beispiel:

![grafik](https://user-images.githubusercontent.com/5215946/35046574-b16f484c-fb97-11e7-9739-26f1e573e4e7.png)
![grafik](https://user-images.githubusercontent.com/5215946/35046587-bee2ff1e-fb97-11e7-9533-9a99c47d1996.png)

## Aktuelles / Fehlerhaftes Verhalten:

Link ist nach dem Deaktivieren der Einstellung immernoch nicht zu sehen.

## Erwartetes Verhalten

Link erscheint jetzt im Menu.

**Comment by xwolfde** [comment]
Danke für den Hinweis. Die Theme Options werden derzeit komplett erneuert (durch Customizer ersetzt), so dass damit dann der Fehler behoben werden sollte.
Leider dauert das noch eine Weile.
Trotzdem sollte man keine externen LInks in die Hauptnavi setzen, sondern dafür die Meta-Navi nutzen.

**Comment by Albager** [comment]
Hängt das vielleicht auch irgendwie damit zusammen, dass es im Header-Menü trotz Haken bei "Link in einem neuen Tab öffnen" nicht funktioniert, dass sich dann auch ein neuer Tab öffnet?
![headermenu_targetblank](https://user-images.githubusercontent.com/11389126/36622138-fe990d98-18fb-11e8-94d6-7af7cef85584.PNG)

**Comment by xwolfde** [comment]
Das hat mit dem obigen nichts zu tun. 
Tabs (Targets) sind grundsätzlich deaktiviert, auch wenn WordPress dummerweise die Option noch bereitstellt. Targets werden von uns nicht nur nicht implementiert, sie werden auch automatisch entfernt, da deren Nutzung noch ein heftigere Barriere verursacht als Links zu externe Seite in einem  Website-spezifischen Menü.

**Comment by Albager** [comment]
OK, dann müssen wir eben ohne neuen Tab für UnivIS leben :-)

**Comment by xwolfde** [comment]
Ext. Link in Hauptmenü ist in der nächsten Version korrigiert
