### ISSUE TITLE
Änderungen von "Startseite"

### ISSUE THREAD

**Issue by michaeldorner** [RRZE-Webteam/FAU-Techfak#43]
Kann ich den Namen des Einsteigspunkt "Startseite" in den breadcrumbs ändern? Gerade für Seiten auf Englisch ist "Startseite" nicht geeignet, eher "Home" oder ähnliches.

**Comment by xwolfde** [comment]
Die Bezeichnung kann man nicht mehr ändern. Grund ist einerseits eine anstehende Änderung/Ergänzung der Breadcrumb um eine Organisatorischen Breadcrumb für die eine Vereinheitlichung gewollt ist, zum anderen aber die Rückmeldung aus einem WCAG-Test einer externen Prüferin, die auch hier die Forderung der Einheitlichen und nachvollziehbaren Navigation gemäß WCAG anmahnte.

Bei englischen Seiten steht da "Start page", was die korrekte Übersetzung ist. Es sei denn, man hat das falsche Englisch gewählt. FAU-Standard (auf Basis eines UL-Beschlusses auf Antrag des Sprachendienstes) ist EN-UK. Bitte dieses auswählen, dann ist die Übersetzung auch richtig.
