### ISSUE TITLE
Blog Post Tags

### ISSUE THREAD

**Issue by georg-schwarz** [RRZE-Webteam/FAU-Techfak#72]
The section "Blog Post Tags" seems broken since the new version.

![image](https://user-images.githubusercontent.com/28054628/166951384-93df6609-89b5-4e7c-85f7-12b0ff68abf2.png)

**Comment by xwolfde** [comment]
nope, its intended

**Comment by dirkriehle** [comment]
It is not a bug, it is a feature?

**Comment by xwolfde** [comment]
Jepp
